version: '3'

services:
  minio:
    image: minio/minio
    command: minio server --console-address ":9001" /data
    environment:
        - MINIO_ACCESS_KEY=$MINIO_ACCESS_KEY
        - MINIO_SECRET_KEY=$MINIO_SECRET_KEY
    ports:
        - "$API_PORT:9000"
        - "$WEB_CONSOLE_PORT:9001"
    volumes:
        - $HOST_MOUNT_PATH:/data